export component MainWindow inherits Window {
    title: "Test Callbacks";
    min-width: 400px;
    min-height: 300px;
    background: #1a5c3a;

    callback test_click();

    Rectangle {
        VerticalBox {
            alignment: center;

            Button {
                text: "CLICK TEST";
                primary: true;
                height: 50px;
                width: 150px;
                clicked => { root.test_click(); }
            }
        }
    }
}
